version: "3.7"
services:

  # Apache HTTP proxy, will forward requests to Boot applications
  proxy:
    container_name: proxy
    build: 
      context: proxy
    ports: 
      - "80:80"
    volumes: 
      - ./proxy/conf:/opt/proxy-conf

  app:
    container_name: app
    build: 
      context: .
    volumes: 
      - ./target/multi-sec.jar:/app/multi-sec.jar
